# Generated by Django 5.2 on 2025-05-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='jins',
            field=models.CharField(choices=[('erkak', 'erkak'), ('ayol', 'ayol')], max_length=20, null=True),
        ),
    ]
